name: OpenWrt Weekly CI
on:
  schedule:
    - cron:  '0 9 * * 5'
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      VERSION: 19.07.2
    steps:
    - name: Checkout - clone repository
      uses: actions/checkout@v1
    - name: Install - system build dependencies
      run: sudo apt install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: Download - openwrt source download
      run: |
        git clone -b openwrt-19.07 https://git.openwrt.org/openwrt/openwrt.git openwrt-$VERSION
    - name: Update - openwrt source update
      run: |
        cd openwrt-$VERSION
        ./scripts/feeds update -a
    - name: Install - openwrt source install
      run: |
        cd openwrt-$VERSION
        ./scripts/feeds install -a
    - name: Replace - openwrt version replace
      run: |
        cd openwrt-$VERSION
        sed -i 's/-SNAPSHOT/.2/g' include/version.mk
    - name: Clone - openwrt plugin source
      run: |
        cd openwrt-$VERSION
        git clone https://github.com/pymumu/smartdns.git ../smartdns && cp -r ../smartdns/package/openwrt/ ./package/smartdns
        git clone https://github.com/LGA1150/openwrt-fullconenat package/fullconenat
        git clone https://github.com/thisdk/k2p-openwrt-mt7615_5.0.2.0.git package/k2p-openwrt-mt7615_5.0.2.0
    - name: Config - copy k2p build config
      run: cp ./.config.19.07.2.release openwrt-$VERSION/.config
    - name: Download - openwrt build dependencies
      run: |
        cd openwrt-$VERSION
        make download -j10
    - name: Build - make openwrt source
      run: |
        cd openwrt-$VERSION
        make -j4
    - name: Remove - delete packages files
      run: |
        cd openwrt-$VERSION/bin/targets/ramips/mt7621/
        rm -rf packages/
        ls -hl
    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: openwrt-k2p
        path: openwrt-${{ env.VERSION }}/bin/targets/ramips/mt7621/
